language: node_js
node_js:
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
services:
  - couchdb
env:
  - COUCH_ADMIN_USERNAME=admin COUCH_ADMIN_PASSWORD=admin
before_script:
  - curl -X PUT http://127.0.0.1:5984/_config/admins/admin -d '"admin"'
script:
  - npm test
  - npm run coverage
  - npm run publish-coverage
notifications:
  slack: standardanalytics:vPQA8IowAphWwzDgGtHkdkRk
